server:
  port: 8082

# Discovery Service Settings
# --------------------------
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
  server:
    enableSelfPreservation: true

# Database properties
spring:
  application:
    name: gitazure-service
  datasource:
    driverClassName: ${DB_DRIVER_CLASS:org.postgresql.Driver}
    platform: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_SERVER_PORT:5432}/${DB_NAME:gitazure}?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: public
        # Set the ddl-auto to none before pushing to production.
        ddl-auto: create-update
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
# API Documentation settings
com.git.azure.configuration:
  security:
    endpoints:
      unsecured:
        - "/v3/api-docs/**"
        - "/swagger-ui.html"
        - "/swagger-ui/**"
    auth:
      token:
        secret: isymphony
        expiration-interval-in-hours: 168
  api:
    documentation:
      title: gitazure-default-service
      description: REPLACE_PROJECT_DESCRIPTION
      # Update the license and licenseUrl.
      license: GNU Lesser General Public License
      licenseUrl: https://www.gnu.org/licenses/lgpl-3.0.en.html
      version: 1.0.0
      contact:
        name: Mahalingam Iyer
        email: Mahalingam Iyer
      base-package: "com.git.azure"
      security-schema:
        name: bearerAuth
        scheme: bearer
        type: HTTP
        bearerFormat: JWT
