# Application name and Config Service URI
# ---------------------------------------
spring:
  application:
    name: discovery-service

# Server Port
# -----------
server:
  port: 8761

# Discovery Service Settings
# --------------------------
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true


# Information that gets displayed in the spring admin UI
# ------------------------------------------------------
info:
  app:
    name: ${spring.application.name}
    description: Discovery Service
